#!/bin/sh
# Copyright 2023 (Holloway) Chew, Kean Ho <hollowaykeanho@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at:
#                http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.




# initialize
if [ "$PROJECT_PATH_ROOT" = "" ]; then
        >&2 printf "[ ERROR ] - Please run from automataCI/ci.sh.ps1 instead!\n"
        return 1
fi




# execute
. "${LIBS_AUTOMATACI}/services/HestiaSTRING/To_Uppercase.sh.ps1"
. "${LIBS_AUTOMATACI}/services/HestiaSTRING/To_Lowercase.sh.ps1"
. "${LIBS_AUTOMATACI}/services/HestiaSTRING/To_Titlecase.sh.ps1"
. "${LIBS_AUTOMATACI}/services/HestiaSTRING/Trim_Prefix.sh.ps1"
. "${LIBS_AUTOMATACI}/services/HestiaSTRING/Trim_Suffix.sh.ps1"
. "${LIBS_AUTOMATACI}/services/HestiaSTRING/Trim_Left.sh.ps1"
. "${LIBS_AUTOMATACI}/services/HestiaSTRING/Trim_Right.sh.ps1"
. "${LIBS_AUTOMATACI}/services/HestiaSTRING/Get_Length.sh.ps1"
. "${LIBS_AUTOMATACI}/services/HestiaSTRING/Has_Any.sh.ps1"
. "${LIBS_AUTOMATACI}/services/HestiaSTRING/Has.sh.ps1"
. "${LIBS_AUTOMATACI}/services/HestiaSTRING/Index_Any_Right.sh.ps1"
. "${LIBS_AUTOMATACI}/services/HestiaSTRING/Index_Any_Left.sh.ps1"
. "${LIBS_AUTOMATACI}/services/HestiaSTRING/Index_Left.sh.ps1"
. "${LIBS_AUTOMATACI}/services/HestiaSTRING/Index_Right.sh.ps1"
. "${LIBS_AUTOMATACI}/services/HestiaSTRING/Scan_Left.sh.ps1"
. "${LIBS_AUTOMATACI}/services/HestiaSTRING/Scan_Right.sh.ps1"
. "${LIBS_AUTOMATACI}/services/HestiaSTRING/Replace_Left.sh.ps1"
. "${LIBS_AUTOMATACI}/services/HestiaSTRING/Replace_Right.sh.ps1"
. "${LIBS_AUTOMATACI}/services/HestiaSTRING/Split_Left.sh.ps1"
. "${LIBS_AUTOMATACI}/services/HestiaSTRING/Split_Right.sh.ps1"
. "${LIBS_AUTOMATACI}/services/HestiaSTRING/To_ID.sh.ps1"

HestiaSTRING_To_Uppercase "aergaegE你F\n\a\oaegeagae\n\n"
printf -- "\n\n"
HestiaSTRING_To_Lowercase "AERGAEGe你F\n\a\oaEgEAgAe\n\n"
printf -- "\n\n"
HestiaSTRING_To_Titlecase "AERGAEGe你F\n\a\o aEgEAgAe\n\n"
printf -- "\n\n"

sample="e你feeeff你你aergaegE你F"
HestiaSTRING_Trim_Prefix "$sample" "e你f"
printf -- "\n"
HestiaSTRING_Trim_Prefix "$sample" "E你F"
printf -- "\n"
HestiaSTRING_Trim_Prefix "" "E你F"
printf -- "\n\n"
HestiaSTRING_Trim_Suffix "$sample" "e你f"
printf -- "\n"
HestiaSTRING_Trim_Suffix "$sample" "E你F"
printf -- "\n"
HestiaSTRING_Trim_Suffix "" "E你F"
printf -- "\n\n"

HestiaSTRING_Trim_Left "$sample" "e你fx"
printf -- "\n"
HestiaSTRING_Trim_Left "$sample" "E你F"
printf -- "\n"
HestiaSTRING_Trim_Left "" "E你F"
printf -- "\n\n"

HestiaSTRING_Trim_Right "$sample" "e你fx"
printf -- "\n"
HestiaSTRING_Trim_Right "$sample" "E你Fx"
printf -- "\n"
HestiaSTRING_Trim_Right "" "E你F"
printf -- "\n\n"

target="你你你你"
HestiaSTRING_Get_Length "$target"
printf -- "\n"
printf -- "${#target}\n"
printf -- "\n\n"


sample="e你feeeff你你aergaegE你F"
HestiaSTRING_Has_Any "$sample" "e你fx"
printf -- "\n"
HestiaSTRING_Has_Any "$sample" "E你F"
printf -- "\n"
HestiaSTRING_Has_Any "$target" "E你F"
printf -- "\n"
HestiaSTRING_Has_Any "" "E你F"
printf -- "\n"
HestiaSTRING_Has_Any "xdn" "E你F"
printf -- "\n\n"


sample="e你feeeff你你aergaegE你F"
HestiaSTRING_Has "$sample" "e你fx"
printf -- "\n"
HestiaSTRING_Has "$sample" "E你F"
printf -- "\n"
HestiaSTRING_Has "$sample" "e你f"
printf -- "\n"
HestiaSTRING_Has "$sample" "你你a"
printf -- "\n"
HestiaSTRING_Has "$target" "E你F"
printf -- "\n"
HestiaSTRING_Has "" "E你F"
printf -- "\n"
HestiaSTRING_Has "xdn" "E你F"
printf -- "\n\n"


sample="e你feeeff你你aergaegE你F"
HestiaSTRING_Index_Any_Right "$sample" "e你fx"
printf -- "\n"
HestiaSTRING_Index_Any_Right "$sample" "E你F"
printf -- "\n"
HestiaSTRING_Index_Any_Right "$sample" "e你f"
printf -- "\n"
HestiaSTRING_Index_Any_Right "$sample" "你"
printf -- "\n"
HestiaSTRING_Index_Any_Right "" "E你F"
printf -- "\n"
HestiaSTRING_Index_Any_Right "xdn" "E你F"
printf -- "\n\n"


sample="e你feeeff你你aergaegE你F"
HestiaSTRING_Index_Any_Left "$sample" "e你fx"
printf -- "\n"
HestiaSTRING_Index_Any_Left "$sample" "E你F"
printf -- "\n"
HestiaSTRING_Index_Any_Left "$sample" "e你f"
printf -- "\n"
HestiaSTRING_Index_Any_Left "$sample" "你"
printf -- "\n"
HestiaSTRING_Index_Any_Left "" "E你F"
printf -- "\n"
HestiaSTRING_Index_Any_Left "xdn" "E你F"
printf -- "\n\n"


sample="e你feeeff你你aergaegE你F"
HestiaSTRING_Index_Left "$sample" "e你fx"
printf -- "\n"
HestiaSTRING_Index_Left "$sample" "E你F"
printf -- "\n"
HestiaSTRING_Index_Left "$sample" "e你f"
printf -- "\n"
HestiaSTRING_Index_Left "$sample" "你"
printf -- "\n"
HestiaSTRING_Index_Left "" "E你F"
printf -- "\n"
HestiaSTRING_Index_Left "xdn" "E你F"
printf -- "\n\n"


sample="e你feeeff你你aergaegE你F"
HestiaSTRING_Index_Right "$sample" "e你fx"
printf -- "\n"
HestiaSTRING_Index_Right "$sample" "E你F"
printf -- "\n"
HestiaSTRING_Index_Right "$sample" "e你f"
printf -- "\n"
HestiaSTRING_Index_Right "$sample" "你"
printf -- "\n"
HestiaSTRING_Index_Right "" "E你F"
printf -- "\n"
HestiaSTRING_Index_Right "xdn" "E你F"
printf -- "\n\n"


sample="e你feeeff你你aergaegE你F"
HestiaSTRING_Scan_Left "$sample" "e你fx"
printf -- "\n"
HestiaSTRING_Scan_Left "$sample" "E你F"
printf -- "\n"
HestiaSTRING_Scan_Left "$sample" "e你f"
printf -- "\n"
HestiaSTRING_Scan_Left "$sample" "你"
printf -- "\n"
HestiaSTRING_Scan_Left "$sample" "你" "2"
printf -- "\n"
HestiaSTRING_Scan_Left "$sample" "你" "2" "1"
printf -- "\n"
HestiaSTRING_Scan_Left "$sample" "你" "-1" "2"
printf -- "\n"
HestiaSTRING_Scan_Left "$sample" "你" "-1" "-1"
printf -- "\n"
HestiaSTRING_Scan_Left "" "E你F"
printf -- "\n"
HestiaSTRING_Scan_Left "xdn" "E你F"
printf -- "\n\n"


sample="e你feeeff你你aergaegE你F"
HestiaSTRING_Scan_Right "$sample" "e你fx"
printf -- "\n"
HestiaSTRING_Scan_Right "$sample" "E你F"
printf -- "\n"
HestiaSTRING_Scan_Right "$sample" "e你f"
printf -- "\n"
HestiaSTRING_Scan_Right "$sample" "你"
printf -- "\n"
HestiaSTRING_Scan_Right "$sample" "你" "2"
printf -- "\n"
HestiaSTRING_Scan_Right "$sample" "你" "2" "1"
printf -- "\n"
HestiaSTRING_Scan_Right "$sample" "你" "-1" "2"
printf -- "\n"
HestiaSTRING_Scan_Right "$sample" "你" "-1" "-1"
printf -- "\n"
HestiaSTRING_Scan_Right "" "E你F"
printf -- "\n"
HestiaSTRING_Scan_Right "xdn" "E你F"
printf -- "\n\n"


sample="e你feeeff你你aergaegE你F"
HestiaSTRING_Replace_Left "$sample" "e你fx" "X我%"
printf -- "\n"
HestiaSTRING_Replace_Left "$sample" "E你F" "X我%"
printf -- "\n"
HestiaSTRING_Replace_Left "$sample" "e你f" "X我%"
printf -- "\n"
HestiaSTRING_Replace_Left "$sample" "你" "我"
printf -- "\n"
HestiaSTRING_Replace_Left "$sample" "你" "X我%" "2"
printf -- "\n"
HestiaSTRING_Replace_Left "$sample" "你" "X我%" "2" "1"
printf -- "\n"
HestiaSTRING_Replace_Left "$sample" "你" "X我%" "-1" "2"
printf -- "\n"
HestiaSTRING_Replace_Left "$sample" "你" "X我%" "-1" "-1"
printf -- "\n"
HestiaSTRING_Replace_Left "" "E你F" "X我%"
printf -- "\n"
HestiaSTRING_Replace_Left "xdn" "E你F" "X我%"
printf -- "\n\n"


sample="e你feeeff你你aergaegE你F"
HestiaSTRING_Replace_Right "$sample" "e你fx" "X我%"
printf -- "\n"
HestiaSTRING_Replace_Right "$sample" "E你F" "X我%"
printf -- "\n"
HestiaSTRING_Replace_Right "$sample" "e你f" "X我%"
printf -- "\n"
HestiaSTRING_Replace_Right "$sample" "你" "我"
printf -- "\n"
HestiaSTRING_Replace_Right "$sample" "你" "X我%" "2"
printf -- "\n"
HestiaSTRING_Replace_Right "$sample" "你" "X我%" "2" "1"
printf -- "\n"
HestiaSTRING_Replace_Right "$sample" "你" "X我%" "-1" "2"
printf -- "\n"
HestiaSTRING_Replace_Right "$sample" "你" "X我%" "-1" "-1"
printf -- "\n"
HestiaSTRING_Replace_Right "" "E你F" "X我%"
printf -- "\n"
HestiaSTRING_Replace_Right "xdn" "E你F" "X我%"
printf -- "\n\n"


sample="e你feeeff你你aergaegE你F"
HestiaSTRING_To_ID "$sample"
printf -- "\n"
HestiaSTRING_To_ID "$sample" "uppercase"
printf -- "\n\n"


sample="e你feeeff你你aergaegE你F"
HestiaSTRING_Split_Left "$sample" "e你fx"
printf -- "\n"
HestiaSTRING_Split_Left "$sample" "E你F"
printf -- "\n"
HestiaSTRING_Split_Left "$sample" "e你f"
printf -- "\n"
HestiaSTRING_Split_Left "$sample" "你"
printf -- "\n"
HestiaSTRING_Split_Left "$sample" "你" "2"
printf -- "\n"
HestiaSTRING_Split_Left "$sample" "你" "2" "1"
printf -- "\n"
HestiaSTRING_Split_Left "$sample" "你" "-1" "2"
printf -- "\n"
HestiaSTRING_Split_Left "$sample" "你" "-1" "-1"
printf -- "\n"
HestiaSTRING_Split_Left "" "E你F"
printf -- "\n"
HestiaSTRING_Split_Left "xdn" "E你F"
printf -- "\n\n"


sample="e你feeeff你你aergaegE你F"
HestiaSTRING_Split_Right "$sample" "e你fx"
printf -- "\n"
HestiaSTRING_Split_Right "$sample" "E你F"
printf -- "\n"
HestiaSTRING_Split_Right "$sample" "e你f"
printf -- "\n"
HestiaSTRING_Split_Right "$sample" "你"
printf -- "\n"
HestiaSTRING_Split_Right "$sample" "你" "2"
printf -- "\n"
HestiaSTRING_Split_Right "$sample" "你" "2" "1"
printf -- "\n"
HestiaSTRING_Split_Right "$sample" "你" "-1" "2"
printf -- "\n"
HestiaSTRING_Split_Right "$sample" "你" "-1" "-1"
printf -- "\n"
HestiaSTRING_Split_Right "" "E你F"
printf -- "\n"
HestiaSTRING_Split_Right "xdn" "E你F"
printf -- "\n\n"


# report status
return 0
